name: Build and Push docker image to registry using workflows.
on:
  push:
    branches: [main]

  
jobs:
  build_push_docker_image:
    name: Build and Push docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code    
      uses: actions/checkout@v4
    
    - name: login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: build image
      run: docker build -t amit2408/jenkins-pipeline-app:latest .
    - name: push image
      run: docker push amit2408/jenkins-pipeline-app:latest
